# Generated by Django 4.1.1 on 2022-10-03 08:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versions',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version', to='taskModel.model'),
        ),
        migrations.CreateModel(
            name='AllocationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(100)])),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_item', to='taskModel.versions')),
            ],
        ),
    ]
