# Generated by Django 4.1.2 on 2022-10-15 15:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taskModel.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskModel', '0002_alter_versions_model_allocationitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('modelFollowed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='taskModel.model')),
            ],
        ),
        migrations.RemoveField(
            model_name='versions',
            name='ISINcode',
        ),
        migrations.RemoveField(
            model_name='versions',
            name='allocation',
        ),
        migrations.RemoveField(
            model_name='versions',
            name='portfolioVersion',
        ),
        migrations.AddField(
            model_name='allocationitem',
            name='ISINcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='versions',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='allocationitem',
            name='weight',
            field=models.DecimalField(decimal_places=3, max_digits=8, validators=[taskModel.models.AllocationItem.minVal, django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='PortfolioAllocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('valueShare', models.DecimalField(decimal_places=3, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_allocations', to='taskModel.portfolio')),
            ],
        ),
    ]
