# Generated by Django 4.1.2 on 2022-10-21 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskModel', '0003_portfolio_remove_versions_isincode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('T1', 'TAG1'), ('T2', 'TAG2'), ('T3', 'TAG3'), ('T4', 'TAG4')], max_length=255)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='taskModel.model')),
            ],
        ),
    ]
